"""
Django settings for stockmarketprediction project.

Generated by 'django-admin startproject' using Django 3.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Static files configuration - using only 'static' directory for both development and production
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# No STATICFILES_DIRS needed as we're using a single directory

# Load environment variables from .env file in the base directory
dotenv_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=dotenv_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7for9)js*2g@04iyh3&#lpa8#_kyrfj58px)07fg1o558z$a^-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin', # Add Jazzmin before admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Add humanize for template filters like intcomma
    'stocks', # Add our stocks app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stockmarketprediction.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add project-level templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockmarketprediction.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# Use SQLite for Django models, direct pymongo for MongoDB data

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # Commented out djongo configuration as it's not compatible with newer Django
    # 'mongodb': {
    #     'ENGINE': 'djongo',
    #     'NAME': os.getenv('MONGO_DB_NAME', 'stock_data'),
    #     'CLIENT': {
    #         'host': os.getenv('MONGO_URI', 'mongodb://localhost:27017/'),
    #         'port': 27017,
    #     }
    # }
}

# Comment out database routers since we're not using djongo
# DATABASE_ROUTERS = ['stockmarketprediction.mongodb_router.MongoDBRouter']

# MongoDB connection for direct pymongo access - we'll use this instead of djongo
MONGO_URI = os.getenv('MONGO_URI', 'mongodb://localhost:27017/')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME', 'stock_data')


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# No STATICFILES_DIRS needed as we're using a single directory

django_heroku.settings(locals())

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Settings (Basic Example)
JAZZMIN_SETTINGS = {
    # title of the window
    "site_title": "StockWise Admin",

    # Title on the login screen
    "site_header": "StockWise",

    # Title on the brand
    "site_brand": "StockWise",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the StockWise Admin",

    # Copyright on the footer
    "copyright": "StockWise Ltd",
    
    # Set to false to remove the Jazzmin version footer text
    "show_footer": False,

    # Disable model search completely
    "search_model": None,

    # Don't show User in sidebar or top menu
    "hide_models": ["auth.User", "auth.Group"],
    
    ############
    # Top Menu #
    ############

    # Links to put along the top menu - simplified with direct URLs only
    "topmenu_links": [
        # Direct URL to admin index - no name/permission logic
        {"name": "Home", "url": "/admin/"},

        # Direct URLs for custom views - no permissions logic
        {"name": "Fetch News", "url": "/admin/stocks/fetch-news/"},
        {"name": "Update All Prices", "url": "/admin/stocks/update-all-prices/"},
        {"name": "Update Commodities", "url": "/admin/stocks/update-commodities/"},
        {"name": "Prediction Dashboard", "url": "/admin/predictions/"},
        
        # Simple app link instead of model
        {"app": "stocks"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right
    "usermenu_links": [
        {"name": "Fetch News", "url": "/admin/stocks/fetch-news/", "new_window": False},
        {"name": "Update All Prices", "url": "/admin/stocks/update-all-prices/", "new_window": False},
        {"name": "Update Commodities", "url": "/admin/stocks/update-commodities/", "new_window": False},
        {"name": "Prediction Dashboard", "url": "/admin/predictions/", "new_window": False},
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to auto expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu
    "hide_apps": ["auth"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "stocks": [{
            "name": "Fetch News", 
            "url": "/admin/stocks/fetch-news/", 
            "icon": "fas fa-newspaper",
        }, {
            "name": "Update All Prices", 
            "url": "/admin/stocks/update-all-prices/", 
            "icon": "fas fa-sync",
        }, {
            "name": "Update Commodities", 
            "url": "/admin/stocks/update-commodities/", 
            "icon": "fas fa-chart-line",
        }, {
            "name": "Prediction Dashboard", 
            "url": "/admin/predictions/", 
            "icon": "fas fa-brain",
        }]
    },

    # Render out the change view as a single form, or in tabs
    "changeform_format": "horizontal_tabs",
    
    # Icons for models in the side menu
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "stocks.Stock": "fas fa-chart-line",
        "stocks.StockNews": "fas fa-newspaper",
        "stocks.Watchlist": "fas fa-list",
        "stocks.WatchlistItem": "fas fa-star",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Authentication settings
LOGIN_REDIRECT_URL = '/'  # Redirect to home page after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to home page after logout

# Increase form field submission limit to handle large stock selections
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increased from 5000 to accommodate more stocks
