# Generated by Django 5.2 on 2025-04-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20250413_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Finnhub', max_length=50)),
                ('headline', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('published_at', models.DateTimeField()),
                ('sentiment_positive', models.FloatField(blank=True, null=True)),
                ('sentiment_negative', models.FloatField(blank=True, null=True)),
                ('sentiment_neutral', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Stock News',
                'ordering': ['-published_at'],
            },
        ),
    ]
