# Generated by Django 5.2 on 2025-04-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_id_alter_watchlist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('SVM', 'Support Vector Machine'), ('XGBOOST', 'XGBoost'), ('SARIMA', 'SARIMA'), ('LSTM', 'LSTM')], max_length=10)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('model_path', models.CharField(max_length=512)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Trained Prediction Models',
                'ordering': ['stock', '-trained_at'],
            },
        ),
    ]
