# Generated by Django 5.2 on 2025-04-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_trainedpredictionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
